### ISSUE TITLE
GLL parser returns error D06 when root symbol has a "deleted" mark

### ISSUE THREAD

**Issue by GuntherRademacher** [nineml/nineml#42] opened 2023-09-26 19:57 UTC
I am using a [JSON grammar](https://github.com/GuntherRademacher/rex-parser-benchmark/blob/abb5d6058fbb63dc40ae0a55693ceb840d08ef05/src/main/resources/de/bottlecaps/rex/benchmark/json/parsers/xquery/json.ixml#L1) where the start symbol has a "deleted" mark. Since 3.0.0, its GLL parser comes up with error code `D06`. 

This worked OK in 2.x versions, and it still does with an Earley parser, or when omitting the "deleted" mark.

**Comment by ndw** [comment] 2023-09-27 12:42
Interesting. I've got both parsers in pieces on the floor around me at the moment, but I'm hoping to get them put back together again "real soon now". Can you send me a copy of the grammar so I can reproduce the problem, please?

**Comment by GuntherRademacher** [comment] 2023-09-27 13:05
This is the link to the grammar:
https://github.com/GuntherRademacher/rex-parser-benchmark/blob/abb5d6058fbb63dc40ae0a55693ceb840d08ef05/src/main/resources/de/bottlecaps/rex/benchmark/json/parsers/xquery/json.ixml

**Comment by ndw** [comment] 2023-10-01 15:03
Turns out that when building the parse forest from a GLL parse, I was turning epsilons into empty strings. This doesn't generally make any difference, but it caused the root of the tree to appear to contain invalid content.

Of course, this is a double-bug because the strings should have been allowed anyway. You're allowed to have whitespace before and after the root element. Also fixed in the second commit.

**Closed** 2023-10-01 15:15 UTC
